### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by plaidscreen** [getkart/kart#17]
I'm open to suggestions here.

For PHP unit testing, I'd like to use [phpt](https://qa.php.net/write-test.php). Reasons are mostly personal preference: it fits into my workflow easily, I can't figure out how to use PHPUnit.

I've already set up a test suite inside the [Events repo](https://github.com/getkart/events/tree/master/tests), it has some good examples of how to use phpt. Setup is fairly simple, on Linux and Mac, you need to install PEAR, and then make sure your PEAR libraries are included in the php.ini include path. (If you need help doing that, ask me.)

After set up, running the test suite is as simple as `pear run-tests tests/*.php`
It tells you if everything passed, if it fails, it tells you what went wrong by outputting a pile of files. (the *.diff is the important one)

Thoughts? Better ideas?

**Comment by plaidscreen** [comment]
For JavaScript unit testing, I'm thinking of using [qUnit](http://qunitjs.com). I've never used it before. To be honest I've never Unit Tested javascript before. Obviously that has to change.

**Comment by distantnative** [comment]
Honestly, I haven't really used unit testing before, but I think it's time to get into it ;)

**Comment by benseitz** [comment]
I never used unit testing before either :O

**Comment by plaidscreen** [comment]
@benseitz @distantnative *Gasp!*

Haha don't worry, I've only got into unit testing in the last year. It's a bit more work up front, but will save you SO MUCH TIME debugging down the road, _especially_ on a big project like this one.

So let's go with phpt for PHP, and QUnit for jQuery/JavaScript. Read up on both, if you need any help getting setup, just ask me!
